=== zhenglincheng/org.eclipse.tm/rse/plugins/org.eclipse.rse.ui/messageFile.dtd
<!ELEMENT Component (Subcomponent+)>
<!ATTLIST Component
 Abbr ID #REQUIRED
 Name CDATA #REQUIRED
>
<!ELEMENT LevelOne (#PCDATA)>
<!ELEMENT LevelTwo (#PCDATA)>
<!ELEMENT Message (LevelOne, LevelTwo)>
<!ATTLIST Message
 ID CDATA #REQUIRED
 Indicator (I | E | W | U | Q | C) #REQUIRED
>
<!ELEMENT MessageFile (Component)>
<!ATTLIST MessageFile
 Version CDATA #FIXED "1.0"
>
<!ELEMENT MessageList (Message+)>
<!ELEMENT Subcomponent (MessageList)>
<!ATTLIST Subcomponent
 Abbr ID #REQUIRED
 Name CDATA #REQUIRED
>

=== zhenglincheng/org.eclipse.tm/rse/examples/org.eclipse.rse.examples.tutorial/rseSamplesMessages.xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE MessageFile SYSTEM "../org.eclipse.rse.ui/messageFile.dtd">
<!-- This is a message file used by SystemMessage and SystemMessageDialog -->
<MessageFile Version="1.0">
	<Component Name="RSE Samples" Abbr="RSS">
		<Subcomponent Name="General" Abbr="G">
			<MessageList>
				<Message ID="1001" Indicator="E">
					<LevelOne>Sample message</LevelOne>		
					<LevelTwo>This is a sample with one substution variable: %1</LevelTwo>
				</Message>
				<Message ID="1002" Indicator="I">
					<LevelOne>Processing...</LevelOne>
					<LevelTwo></LevelTwo>
				</Message>
			</MessageList>
		</Subcomponent>
	</Component>
</MessageFile>

=== zhenglincheng/org.eclipse.tm/rse/plugins/org.eclipse.rse.processes.ui/processmessages.xml
<?xml version="1.0" encoding='UTF-8'?>
<!--
Copyright (c) 2006 IBM Corporation. All rights reserved.
This program and the accompanying materials are made available under the terms
of the Eclipse Public License v1.0 which accompanies this distribution, and is 
available at http://www.eclipse.org/legal/epl-v10.html

Initial Contributors:
The following IBM employees contributed to the Remote System Explorer
component that contains this file: David McKnight, Kushal Munir, 
Michael Berger, David Dykstal, Phil Coulthard, Don Yantzi, Eric Simpson, 
Emily Bruner, Mazen Faraj, Adrian Storisteanu, Li Ding, and Kent Hawley.

Contributors:
{Name} (company) - description of contribution.
-->
<!DOCTYPE MessageFile SYSTEM "messageFile.dtd">

<MessageFile Version="1.0">
     <Component Name="Remote_System_Explorer_Processes" Abbr="RSEP">
          <Subcomponent Name="General" Abbr="G">
                <MessageList>
                    <Message ID="1001" Indicator="E">
                          <LevelOne>Maximum VM size must be greater than minimum VM size.</LevelOne>
                          <LevelTwo></LevelTwo>
                    </Message>
                    <Message ID="1002" Indicator="E">
                          <LevelOne>You do not have permission to kill the process.</LevelOne>
                          <LevelTwo>You must own the process or be root in order to kill this process.</LevelTwo>
                    </Message>
                    <Message ID="1003" Indicator="I">
                          <LevelOne>Sending a kill signal...</LevelOne>		
                          <LevelTwo></LevelTwo>
                    </Message>
                    <Message ID="1004" Indicator="I">
                          <LevelOne>Sending the signal %1 to the process %2...</LevelOne>		
                          <LevelTwo></LevelTwo>
                    </Message>
                    <Message ID="1300" Indicator="E">
                        <LevelOne>Kill of the process %1 failed</LevelOne>
                        <LevelTwo>The remote system reported the following: %2</LevelTwo>
                    </Message>
                    <Message ID="1301" Indicator="E">
                        <LevelOne>Problem occurred during remote process query</LevelOne>
                        <LevelTwo>Could not access the /proc filesystem. You might not have permission to access it.</LevelTwo>
                    </Message>
                </MessageList>
          </Subcomponent>
     </Component>
</MessageFile>
